<?php
use App\Http\Controllers\{DashboardController,GuestController,InvitationController,OrderController,PublicInvitationController};
use App\Http\Controllers\Admin\AdminController; use App\Http\Controllers\Auth\AuthController; use Illuminate\Support\Facades\Route;
Route::get('/', function(\Illuminate\Http\Request $request){$host=$request->getHost();$inv=\App\Models\Invitation::where('custom_domain',$host)->where('is_published',true)->first();if($inv){$inv->increment('views_count');return view('public.invitation',['invitation'=>$inv,'guest'=>null,'wishes'=>$inv->wishes()->where('is_approved',true)->take(30)->get(),'photos'=>$inv->photos()->where('status','approved')->take(50)->get()]);}return view('welcome');})->name('home');
Route::middleware('guest')->group(function(){Route::get('/login',[AuthController::class,'loginForm'])->name('login');Route::post('/login',[AuthController::class,'login']);Route::get('/register',[AuthController::class,'registerForm'])->name('register');Route::post('/register',[AuthController::class,'register']);});
Route::post('/logout',[AuthController::class,'logout'])->middleware('auth')->name('logout');
Route::get('/u/{slug}',[PublicInvitationController::class,'show'])->name('public.invitation');
Route::post('/u/{invitation}/rsvp',[PublicInvitationController::class,'rsvp'])->name('public.rsvp');
Route::post('/u/{invitation}/photo',[PublicInvitationController::class,'photo'])->name('public.photo');
Route::get('/checkin/{invitation}/{guest}',[PublicInvitationController::class,'checkin'])->middleware('signed')->name('public.checkin');
Route::middleware('auth')->group(function(){Route::get('/dashboard',DashboardController::class)->name('dashboard');Route::resource('invitations',InvitationController::class)->except(['index','show']);Route::post('/invitations/{invitation}/publish',[InvitationController::class,'publish'])->name('invitations.publish');Route::get('/invitations/{invitation}/guests',[GuestController::class,'index'])->name('guests.index');Route::post('/invitations/{invitation}/guests',[GuestController::class,'store'])->name('guests.store');Route::delete('/invitations/{invitation}/guests/{guest}',[GuestController::class,'destroy'])->name('guests.destroy');Route::get('/invitations/{invitation}/guests-export',[GuestController::class,'export'])->name('guests.export');Route::post('/invitations/{invitation}/orders',[OrderController::class,'store'])->name('orders.store');});
Route::middleware(['auth','admin'])->prefix('admin')->name('admin.')->group(function(){Route::get('/',[AdminController::class,'index'])->name('index');Route::post('/orders/{order}/verify',[AdminController::class,'verify'])->name('orders.verify');Route::post('/photos/{photo}/{status}',[AdminController::class,'photo'])->name('photos.moderate');});
