<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        $canvas = [
            'version' => 4,
            'width' => 390,
            'height' => 844,
            'settings' => [
                'desktopLayout' => 'cover-left',
                'desktopCoverWidth' => 52,
                'mobileBreakpoint' => 768,
            ],

            // Basic template: visual design is controlled by Admin.
            // Customer only supplies bound content/media through the Basic editor.
            'desktopCover' => [
                'image' => '',
                'mediaType' => 'image',
                'fit' => 'cover',
                'scale' => 1,
                'posX' => 0,
                'posY' => 0,
                'background' => '#18231F',
            ],

            'openingCover' => [
                'enabled' => true,
                'eyebrow' => 'THE WEDDING OF',
                'names' => 'Nama & Nama',
                'bindNames' => true,
                'buttonText' => 'Buka Undangan',
                'textColor' => '#FFF9EF',
                'buttonColor' => '#B86B4B',
                'nameSize' => 45,
                'posX' => 50,
                'posY' => 50,
                'animation' => 'fade-up',
                'duration' => 0.8,
                'background' => '#18231F',
            ],

            'pages' => [
                [
                    'id' => 'basic-senja-hero',
                    'name' => 'Opening',
                    'role' => 'hero',
                    'width' => 390,
                    'height' => 844,
                    'background' => '#F7F1E7',
                    'transition' => ['type' => 'fade', 'duration' => 0.8, 'easing' => 'ease-in-out'],
                    'layers' => [
                        [
                            'id' => 'hero-accent-top',
                            'type' => 'shape',
                            'name' => 'Accent',
                            'shapeKind' => 'rect',
                            'x' => 0, 'y' => 0, 'width' => 390, 'height' => 18,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 1,
                            'background' => '#B86B4B',
                            'borderRadius' => 0,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'hero-kicker',
                            'type' => 'text',
                            'name' => 'Kicker',
                            'text' => 'THE WEDDING OF',
                            'binding' => 'none',
                            'x' => 45, 'y' => 75, 'width' => 300, 'height' => 26,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 3,
                            'fontFamily' => 'Arial', 'fontSize' => 12, 'fontWeight' => 700,
                            'fontStyle' => 'normal', 'color' => '#B86B4B', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0, 'lineHeight' => 1.3,
                            'locked' => true, 'hidden' => false,
                            'animation' => 'fade-up', 'duration' => 0.7, 'delay' => 0.05, 'loop' => false,
                        ],
                        [
                            'id' => 'hero-photo',
                            'type' => 'frame',
                            'name' => 'Foto Pasangan',
                            'binding' => 'couple_photo',
                            'x' => 55, 'y' => 125, 'width' => 280, 'height' => 360,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'borderRadius' => 140,
                            'cells' => [['src' => null, 'posX' => 0, 'posY' => 0, 'scale' => 1]],
                            'optional' => true, 'hideWhenEmpty' => false,
                            'locked' => true, 'hidden' => false,
                            'animation' => 'soft-scale', 'duration' => 0.8, 'delay' => 0.1, 'loop' => false,
                        ],
                        [
                            'id' => 'hero-names',
                            'type' => 'text',
                            'name' => 'Nama Pasangan',
                            'text' => 'Nama & Nama',
                            'binding' => 'couple_names',
                            'x' => 25, 'y' => 520, 'width' => 340, 'height' => 82,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 5,
                            'fontFamily' => 'Georgia', 'fontSize' => 40, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#18231F', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0, 'lineHeight' => 1.05,
                            'locked' => true, 'hidden' => false,
                            'animation' => 'fade-up', 'duration' => 0.8, 'delay' => 0.15, 'loop' => false,
                        ],
                        [
                            'id' => 'hero-opening-text',
                            'type' => 'text',
                            'name' => 'Teks Pembuka',
                            'text' => 'Dengan penuh sukacita, kami mengundang Anda untuk merayakan hari bahagia kami.',
                            'binding' => 'opening_text',
                            'x' => 48, 'y' => 615, 'width' => 294, 'height' => 82,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 5,
                            'fontFamily' => 'Arial', 'fontSize' => 15, 'fontWeight' => 400,
                            'fontStyle' => 'normal', 'color' => '#4C5B55', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0, 'lineHeight' => 1.55,
                            'locked' => true, 'hidden' => false,
                            'animation' => 'fade-up', 'duration' => 0.8, 'delay' => 0.2, 'loop' => false,
                        ],
                        [
                            'id' => 'hero-event-date',
                            'type' => 'text',
                            'name' => 'Tanggal Acara',
                            'text' => 'Tanggal Acara',
                            'binding' => 'event_date',
                            'x' => 55, 'y' => 725, 'width' => 280, 'height' => 38,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 5,
                            'fontFamily' => 'Arial', 'fontSize' => 13, 'fontWeight' => 700,
                            'fontStyle' => 'normal', 'color' => '#B86B4B', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0, 'lineHeight' => 1.3,
                            'locked' => true, 'hidden' => false,
                        ],
                    ],
                ],

                [
                    'id' => 'basic-senja-couple',
                    'name' => 'Mempelai & Cerita',
                    'role' => 'content',
                    'width' => 390,
                    'height' => 1080,
                    'background' => '#FFFDF9',
                    'transition' => ['type' => 'fade', 'duration' => 0.8, 'easing' => 'ease-in-out'],
                    'layers' => [
                        [
                            'id' => 'couple-title',
                            'type' => 'text',
                            'name' => 'Judul Mempelai',
                            'text' => 'Dua Hati, Satu Cerita',
                            'binding' => 'none',
                            'x' => 35, 'y' => 70, 'width' => 320, 'height' => 50,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Georgia', 'fontSize' => 29, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#18231F', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0, 'lineHeight' => 1.2,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'groom-photo',
                            'type' => 'frame',
                            'name' => 'Foto Pria',
                            'binding' => 'groom_photo',
                            'x' => 35, 'y' => 155, 'width' => 145, 'height' => 205,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'borderRadius' => 72,
                            'cells' => [['src' => null, 'posX' => 0, 'posY' => 0, 'scale' => 1]],
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'bride-photo',
                            'type' => 'frame',
                            'name' => 'Foto Wanita',
                            'binding' => 'bride_photo',
                            'x' => 210, 'y' => 155, 'width' => 145, 'height' => 205,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'borderRadius' => 72,
                            'cells' => [['src' => null, 'posX' => 0, 'posY' => 0, 'scale' => 1]],
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'groom-name',
                            'type' => 'text',
                            'name' => 'Nama Pria',
                            'text' => 'Nama Pria',
                            'binding' => 'groom_name',
                            'x' => 28, 'y' => 385, 'width' => 160, 'height' => 46,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 3,
                            'fontFamily' => 'Georgia', 'fontSize' => 24, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#18231F', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'bride-name',
                            'type' => 'text',
                            'name' => 'Nama Wanita',
                            'text' => 'Nama Wanita',
                            'binding' => 'bride_name',
                            'x' => 202, 'y' => 385, 'width' => 160, 'height' => 46,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 3,
                            'fontFamily' => 'Georgia', 'fontSize' => 24, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#18231F', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'quote-label',
                            'type' => 'text',
                            'name' => 'Quote Label',
                            'text' => '“',
                            'binding' => 'none',
                            'x' => 40, 'y' => 475, 'width' => 310, 'height' => 55,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 1,
                            'fontFamily' => 'Georgia', 'fontSize' => 48, 'fontWeight' => 700,
                            'fontStyle' => 'normal', 'color' => '#B86B4B', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'quote-text',
                            'type' => 'text',
                            'name' => 'Quote',
                            'text' => 'Cinta adalah perjalanan pulang menuju satu sama lain.',
                            'binding' => 'quote',
                            'x' => 45, 'y' => 530, 'width' => 300, 'height' => 115,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Georgia', 'fontSize' => 18, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#4C5B55', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0, 'lineHeight' => 1.55,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'story-title',
                            'type' => 'text',
                            'name' => 'Story Title',
                            'text' => 'Cerita Kami',
                            'binding' => 'none',
                            'x' => 45, 'y' => 700, 'width' => 300, 'height' => 45,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Georgia', 'fontSize' => 27, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#18231F', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'story-text',
                            'type' => 'text',
                            'name' => 'Love Story',
                            'text' => 'Tulis perjalanan singkat kalian di sini.',
                            'binding' => 'story',
                            'x' => 42, 'y' => 765, 'width' => 306, 'height' => 220,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Arial', 'fontSize' => 15, 'fontWeight' => 400,
                            'fontStyle' => 'normal', 'color' => '#4C5B55', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0, 'lineHeight' => 1.65,
                            'locked' => true, 'hidden' => false,
                        ],
                    ],
                ],

                [
                    'id' => 'basic-senja-event',
                    'name' => 'Acara',
                    'role' => 'event',
                    'width' => 390,
                    'height' => 1080,
                    'background' => '#18231F',
                    'transition' => ['type' => 'fade', 'duration' => 0.8, 'easing' => 'ease-in-out'],
                    'layers' => [
                        [
                            'id' => 'event-title',
                            'type' => 'text',
                            'name' => 'Event Title',
                            'text' => 'Save The Date',
                            'binding' => 'none',
                            'x' => 35, 'y' => 70, 'width' => 320, 'height' => 58,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Georgia', 'fontSize' => 32, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#FFF9EF', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'event-date',
                            'type' => 'text',
                            'name' => 'Tanggal',
                            'text' => 'Tanggal Acara',
                            'binding' => 'event_date',
                            'x' => 45, 'y' => 155, 'width' => 300, 'height' => 52,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Arial', 'fontSize' => 18, 'fontWeight' => 700,
                            'fontStyle' => 'normal', 'color' => '#D99B7D', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'countdown-component',
                            'type' => 'shape',
                            'name' => 'Countdown',
                            'componentType' => 'countdown',
                            'x' => 35, 'y' => 240, 'width' => 320, 'height' => 180,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'background' => '#24342E',
                            'borderRadius' => 20,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'venue-name',
                            'type' => 'text',
                            'name' => 'Nama Lokasi',
                            'text' => 'Lokasi Acara',
                            'binding' => 'venue_name',
                            'x' => 40, 'y' => 485, 'width' => 310, 'height' => 55,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Georgia', 'fontSize' => 26, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#FFF9EF', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'venue-address',
                            'type' => 'text',
                            'name' => 'Alamat',
                            'text' => 'Alamat acara',
                            'binding' => 'venue_address',
                            'x' => 50, 'y' => 555, 'width' => 290, 'height' => 90,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Arial', 'fontSize' => 14, 'fontWeight' => 400,
                            'fontStyle' => 'normal', 'color' => '#D8E0DC', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0, 'lineHeight' => 1.55,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'location-component',
                            'type' => 'shape',
                            'name' => 'Maps',
                            'componentType' => 'location',
                            'x' => 45, 'y' => 690, 'width' => 300, 'height' => 220,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'background' => '#FFF9EF',
                            'borderRadius' => 20,
                            'locked' => true, 'hidden' => false,
                        ],
                    ],
                ],

                [
                    'id' => 'basic-senja-gallery',
                    'name' => 'Gallery',
                    'role' => 'gallery',
                    'width' => 390,
                    'height' => 1050,
                    'background' => '#F7F1E7',
                    'transition' => ['type' => 'fade', 'duration' => 0.8, 'easing' => 'ease-in-out'],
                    'layers' => [
                        [
                            'id' => 'gallery-title',
                            'type' => 'text',
                            'name' => 'Gallery Title',
                            'text' => 'Our Moments',
                            'binding' => 'none',
                            'x' => 45, 'y' => 65, 'width' => 300, 'height' => 52,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Georgia', 'fontSize' => 30, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#18231F', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'gallery-1',
                            'type' => 'image',
                            'name' => 'Gallery 1',
                            'binding' => 'gallery_1',
                            'src' => '',
                            'x' => 30, 'y' => 155, 'width' => 330, 'height' => 300,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fit' => 'cover', 'scale' => 1, 'posX' => 0, 'posY' => 0,
                            'borderRadius' => 22,
                            'optional' => true, 'hideWhenEmpty' => false,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'gallery-2',
                            'type' => 'image',
                            'name' => 'Gallery 2',
                            'binding' => 'gallery_2',
                            'src' => '',
                            'x' => 30, 'y' => 480, 'width' => 158, 'height' => 250,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fit' => 'cover', 'scale' => 1, 'posX' => 0, 'posY' => 0,
                            'borderRadius' => 18,
                            'optional' => true, 'hideWhenEmpty' => false,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'gallery-3',
                            'type' => 'image',
                            'name' => 'Gallery 3',
                            'binding' => 'gallery_3',
                            'src' => '',
                            'x' => 202, 'y' => 480, 'width' => 158, 'height' => 250,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fit' => 'cover', 'scale' => 1, 'posX' => 0, 'posY' => 0,
                            'borderRadius' => 18,
                            'optional' => true, 'hideWhenEmpty' => false,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'prayer-text',
                            'type' => 'text',
                            'name' => 'Doa',
                            'text' => 'Semoga langkah kami selalu dipenuhi cinta dan kebaikan.',
                            'binding' => 'prayer',
                            'x' => 50, 'y' => 800, 'width' => 290, 'height' => 120,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Georgia', 'fontSize' => 17, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#4C5B55', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0, 'lineHeight' => 1.55,
                            'locked' => true, 'hidden' => false,
                        ],
                    ],
                ],

                [
                    'id' => 'basic-senja-rsvp',
                    'name' => 'RSVP & Wishes',
                    'role' => 'rsvp',
                    'width' => 390,
                    'height' => 1180,
                    'background' => '#FFFDF9',
                    'transition' => ['type' => 'fade', 'duration' => 0.8, 'easing' => 'ease-in-out'],
                    'layers' => [
                        [
                            'id' => 'rsvp-title',
                            'type' => 'text',
                            'name' => 'RSVP Title',
                            'text' => 'Konfirmasi Kehadiran',
                            'binding' => 'none',
                            'x' => 35, 'y' => 65, 'width' => 320, 'height' => 52,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Georgia', 'fontSize' => 28, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#18231F', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'rsvp-component',
                            'type' => 'shape',
                            'name' => 'RSVP',
                            'componentType' => 'rsvp',
                            'x' => 30, 'y' => 145, 'width' => 330, 'height' => 380,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'background' => '#F7F1E7',
                            'borderRadius' => 20,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'wishes-component',
                            'type' => 'shape',
                            'name' => 'Wishes',
                            'componentType' => 'wishes',
                            'x' => 30, 'y' => 575, 'width' => 330, 'height' => 430,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'background' => '#18231F',
                            'borderRadius' => 20,
                            'locked' => true, 'hidden' => false,
                        ],
                    ],
                ],

                [
                    'id' => 'basic-senja-closing',
                    'name' => 'Closing',
                    'role' => 'closing',
                    'width' => 390,
                    'height' => 760,
                    'background' => '#18231F',
                    'transition' => ['type' => 'fade', 'duration' => 0.8, 'easing' => 'ease-in-out'],
                    'layers' => [
                        [
                            'id' => 'closing-kicker',
                            'type' => 'text',
                            'name' => 'Closing Kicker',
                            'text' => 'TERIMA KASIH',
                            'binding' => 'none',
                            'x' => 45, 'y' => 155, 'width' => 300, 'height' => 30,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Arial', 'fontSize' => 12, 'fontWeight' => 700,
                            'fontStyle' => 'normal', 'color' => '#D99B7D', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'closing-text',
                            'type' => 'text',
                            'name' => 'Teks Penutup',
                            'text' => 'Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Anda berkenan hadir.',
                            'binding' => 'closing_text',
                            'x' => 45, 'y' => 225, 'width' => 300, 'height' => 150,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Georgia', 'fontSize' => 18, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#FFF9EF', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0, 'lineHeight' => 1.6,
                            'locked' => true, 'hidden' => false,
                        ],
                        [
                            'id' => 'closing-names',
                            'type' => 'text',
                            'name' => 'Nama Pasangan',
                            'text' => 'Nama & Nama',
                            'binding' => 'couple_names',
                            'x' => 35, 'y' => 440, 'width' => 320, 'height' => 76,
                            'rotation' => 0, 'opacity' => 1, 'zIndex' => 2,
                            'fontFamily' => 'Georgia', 'fontSize' => 36, 'fontWeight' => 400,
                            'fontStyle' => 'italic', 'color' => '#FFF9EF', 'textAlign' => 'center',
                            'background' => 'transparent', 'borderRadius' => 0,
                            'locked' => true, 'hidden' => false,
                        ],
                    ],
                ],
            ],
        ];

        DB::table('studio_templates')->updateOrInsert(
            ['slug' => 'basic-senja-minimal'],
            [
                'name' => 'Senja Minimal — Basic',
                'status' => 'published',
                'min_plan' => 'basic',
                'is_customer_editable' => false,
                'canvas' => json_encode($canvas, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
                'settings' => json_encode([
                    'package' => 'basic',
                    'customer_mode' => 'data_media_only',
                    'locked_design' => true,
                    'included_features' => [
                        'opening_cover',
                        'couple_profile',
                        'story',
                        'countdown',
                        'location_maps',
                        'gallery_3',
                        'rsvp',
                        'wishes',
                        'closing',
                    ],
                    'excluded_features' => [
                        'blank_canvas',
                        'full_studio_editor',
                        'gift',
                        'guest_photo',
                        'custom_music',
                    ],
                    'seeded_by' => 'UNDANGANTA_BASIC_TEMPLATE_SENJA_MINIMAL_V1',
                ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
                'thumbnail_path' => null,
                'created_by' => null,
                'updated_at' => $now,
                'created_at' => $now,
            ]
        );
    }

    public function down(): void
    {
        DB::table('studio_templates')
            ->where('slug', 'basic-senja-minimal')
            ->delete();
    }
};
