<?php
namespace App\Http\Controllers;
use App\Models\Invitation; use App\Models\Plan; use Illuminate\Http\Request; use Illuminate\Support\Str;
class InvitationController extends Controller {
 public function create(){return view('invitations.form',['invitation'=>new Invitation]);}
 public function store(Request $r){$d=$this->data($r);$d['slug']=$d['slug']?:Str::slug($d['title']).'-'.Str::lower(Str::random(5));$inv=$r->user()->invitations()->create($d);return redirect()->route('invitations.edit',$inv)->with('ok','Undangan dibuat.');}
 public function edit(Invitation $invitation){$this->authorize('update',$invitation);return view('invitations.form',['invitation'=>$invitation,'plans'=>Plan::where('is_active',true)->orderBy('price')->get()]);}
 public function update(Request $r,Invitation $invitation){$this->authorize('update',$invitation);$invitation->update($this->data($r,$invitation));return back()->with('ok','Perubahan disimpan.');}
 public function destroy(Invitation $invitation){$this->authorize('delete',$invitation);$invitation->delete();return redirect()->route('dashboard')->with('ok','Undangan dihapus.');}
 public function publish(Invitation $invitation){$this->authorize('update',$invitation);$invitation->update(['is_published'=>!$invitation->is_published]);return back()->with('ok',$invitation->is_published?'Undangan dipublikasikan.':'Undangan dijadikan draft.');}
 private function data(Request $r, ?Invitation $invitation=null): array { $d=$r->validate(['title'=>'required|max:150','slug'=>'nullable|max:160|regex:/^[a-z0-9-]+$/','groom_name'=>'required|max:100','bride_name'=>'required|max:100','event_date'=>'required|date','venue_name'=>'required|max:160','venue_address'=>'nullable|max:500','maps_url'=>'nullable|url','theme'=>'required|in:classic,modern,minimal,floral','music_url'=>'nullable|url','quote'=>'nullable|max:500','story'=>'nullable|max:5000','custom_domain'=>'nullable|max:255','cover'=>'nullable|image|max:8192','gallery.*'=>'nullable|image|max:8192','gift_bank'=>'nullable|max:100','gift_number'=>'nullable|max:100','gift_name'=>'nullable|max:100']);$d['sections']=['story'=>$r->boolean('section_story'),'gallery'=>$r->boolean('section_gallery'),'gift'=>$r->boolean('section_gift'),'wishes'=>$r->boolean('section_wishes')]; if($r->hasFile('cover')) $d['cover_path']=$r->file('cover')->store('covers','public'); if($r->hasFile('gallery')){ $existing=$invitation?->gallery??[]; foreach($r->file('gallery') as $file){$existing[]=$file->store('gallery','public');} $d['gallery']=$existing; } if($r->filled('gift_bank')) $d['gift_accounts']=[['bank'=>$r->gift_bank,'number'=>$r->gift_number,'name'=>$r->gift_name]]; unset($d['cover'],$d['gift_bank'],$d['gift_number'],$d['gift_name']); return $d; }
}
